-- Create new table for feedback
CREATE TABLE IF NOT EXISTS user_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  feedback TEXT NOT NULL,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE user_feedback ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to insert feedback
CREATE POLICY "Users can insert their own feedback" ON user_feedback FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

-- Allow admins to view all feedback (assuming admin role check or open for now)
CREATE POLICY "Admins can view all feedback" ON user_feedback FOR SELECT TO authenticated USING (true);
